### ISSUE TITLE
Setup testing/CI scaffolding

### ISSUE THREAD

**Issue by zklaus** [SciTools-incubator/iris-esmf-regrid#3]
I think we need some testing and CI stuff. Then we can start by adding test cases for simple regridding based on common grids (such as tripolar, regular, reduced gaussian, ...)

**Comment by stephenworsley** [comment]
I had already written some tests for iris-ugrid here https://github.com/SciTools-incubator/iris-ugrid/blob/master/iris_ugrid/tests/test_regrid.py. I didn't include these in the PR since they involve regridding with meshes. If the iris-ugrid test setup seems appropriate to you, I can start writing an equivalent test in this repo.

**Comment by zklaus** [comment]
I see that in ugrid there is something about travis and stickler, but I'd like to wrap my head around testing infrastructure a bit before adding specific tests.

**Comment by bjlittle** [comment]
I'm happy to contribute to this :+1:

**Comment by bjlittle** [comment]
Might suggest using https://cirrus-ci.org/ instead of travis-ci
