### ISSUE TITLE
Is the fix from PR 353 compatible with esmpy<8.6.0 as well?

### ISSUE THREAD

**Issue by valeriupredoi** [SciTools-incubator/iris-esmf-regrid#415]
Hey folks, we are hitting some environment solving issues, and would like to use `esmpy/esmf<8.6.0` (specifically, 8.4.2) but we are a bit scared that the fix from https://github.com/SciTools-incubator/iris-esmf-regrid/pull/353 will not work for those esmf/esmpy's - could one of you folks confirm we are good to use `esmf/esmpy==8.4.2` and still benefit from the fix, please? Many thanks in advance! Cheers :beer:

**Comment by stephenworsley** [comment]
@valeriupredoi I believe this fix should be backwards compatible. ESMF became more strict about the format it expects indices to be given in (UGRID allows both 0 indexing and 1 indexing), this fix changes the format to be compatible with ESMF>8.6 while remaining otherwise equivalent. The only thing this fix changes is that the indexing format on the original cubes used passed down "as is" to ESMF, but I doubt that was ever relevant.

**Comment by valeriupredoi** [comment]
brilliant, thank you heaps @stephenworsley :beer: Phew! @schlunma we can the still be fine environment-wise, bud
